"""API input and response models."""
from datetime import datetime
from enum import StrEnum
from pathlib import Path
from typing import Annotated, Literal, Mapping, TypeAlias
from pydantic import BaseModel, Field

from bonsai_libs.types.common import Model, IgnoreExtraModelMixin

Headers: TypeAlias = dict[str, str]
OpHeaders: TypeAlias = Headers | None 


class Visibility(StrEnum):
    """Determines the visibilty of a record."""

    PRIVATE = "private"
    ORG = "organization"
    PUBLIC = "public"


class SequencingPlatforms(StrEnum):
    """Supported sequencing platforms."""

    ILLUMUNA = "illumina"
    IONTORRENT = "ion torrent"
    ONT = "oxford nanopore technologies"
    BGI = "bgi"
    PACBIO = "Pacific Biosciences"


class SequencingInfo(Model, IgnoreExtraModelMixin):
    """Information on the sample was sequenced."""

    sequencing_run_id: str
    platform: SequencingPlatforms
    instrument: str | None = None
    method: dict[str, str] = Field(default_factory=dict)
    sequenced_at: datetime | None = None


class GenericMetadataEntry(Model):
    """Container of basic metadata information"""

    fieldname: str
    value: str | int | float
    category: str
    type: Literal["string", "integer", "float"]


class DatetimeMetadataEntry(Model):
    """Container of basic metadata information"""

    fieldname: str
    value: datetime
    category: str
    type: Literal["datetime"] = "datetime"


class InputTableMetadata(Model):
    """Metadata table info recieved by API."""

    fieldname: str
    value: str
    category: str = "general"
    type: Literal["table"] = "table"


InputMetaEntry = Annotated[
    DatetimeMetadataEntry
    | InputTableMetadata
    | GenericMetadataEntry,
    Field(discriminator='type')
]

class InputSampleInfo(Model, IgnoreExtraModelMixin):  # pylint: disable=too-few-public-methods
    """Defines output structure of group info used for creation."""

    sample_id: str | None = None
    sample_name: str
    lims_id: str | None = None

    sequencing: SequencingInfo | None = None
    metadata: list[InputMetaEntry] = Field(default_factory=list)

    # preparation for role based access controll
    owners: list[str] = Field(default_factory=list, description="Owner identifiers (user:<id>)")
    owner_organizations: list[str] = Field(default_factory=list, description="Organization ids (org:<id>)")
    access_groups: list[str] = Field(default_factory=list, description="Optional access groups")
    visibility: Visibility = Visibility.PUBLIC

class CreateSampleResponse(BaseModel):
    """Expected response data when creating a sample."""

    inserted_id: str
    internal_sample_id: str
    external_sample_id: str


class UploadAnalysisResultInput(BaseModel):
    """API input for uploading analysis results."""

    sample_id: str
    pipeline_run_id: str | None = None

    # result
    software: str
    software_version: str
    file: Path


class UploadResultMeta(BaseModel):
    """Additional metadata about the uploaded result."""

    status: int
    request_id: str | None = None


class UploadAnalysisResultResponse(BaseModel):
    """API response after uploading analysis results."""

    sample_id: str
    pipeline_run_id: str | None = None
    analysis_id: str

    # result
    software: str
    software_version: str
    envelopes: Mapping[str, str | None] = Field(default_factory=dict)
    meta: UploadResultMeta | None = None


class PipelineArtifact(BaseModel):
    """Describe a file generated by the pipeline."""

    software_name: str
    software_version: str
    uri: str


class PipelineDefinition(BaseModel):
    """Static metadata about the pipeline code itself."""

    name: str
    version: str
    commit: str | None = None
    release_life_cycle: str | None = None


class PipelineRunConfig(BaseModel):
    """Configuration used for this specific execution."""

    command: str
    analysis_profile: list[str] = Field(default_factory=list)
    configuration_files: list[str] = Field(default_factory=list)


class PipelineInfo(BaseModel):
    """Full description of the pipeline and its execution."""

    definition: PipelineDefinition
    run_config: PipelineRunConfig
    artifacts: list[PipelineArtifact] = Field(default_factory=list)


class InputPipelineRun(IgnoreExtraModelMixin):
    """Describe a execution of a pipeline."""

    pipeline_run_id: str
    executed_at: datetime
    assay: str
    pipeline_info: PipelineInfo
